<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Understanding and accessing LINEAR and ZTF data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/libs/clipboard/clipboard.min.js"></script>
<script src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/libs/quarto-html/quarto.js"></script>
<script src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/libs/quarto-html/popper.min.js"></script>
<script src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/libs/quarto-html/anchor.min.js"></script>
<link href="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Understanding and accessing LINEAR and ZTF data</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><em>Authors: Ema Donev and dr. Ivezić</em></p>
<p>This notebook contains all the information necessary to understand the data, its descriptive statistics, and how to plot light curves of both <code>LINEAR</code> and <code>ZTF</code> data.</p>
<section id="importing-necessary-libraries-and-configuration" class="level3">
<h3 class="anchored" data-anchor-id="importing-necessary-libraries-and-configuration">Importing necessary libraries and configuration</h3>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># IMPORTING LIBRARIES</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># --------------------</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># AstroML</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> astroML.datasets <span class="im">import</span> fetch_LINEAR_sample</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># ZTF</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ztfquery <span class="im">import</span> lightcurve</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Basic libraries</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pickle</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tqdm <span class="im">import</span> tqdm</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> ticker</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.colors <span class="im">as</span> mcolors</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.font_manager <span class="im">import</span> FontProperties</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co"># DataFrame analysis</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> dask.dataframe <span class="im">as</span> dd </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Math libraries</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy <span class="im">as</span> sc</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Multithreading/multiprocessing libraries</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> concurrent.futures <span class="im">import</span> ThreadPoolExecutor</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> concurrent.futures <span class="im">import</span> ProcessPoolExecutor</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> threading</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CONFIG</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>sns.set_theme() <span class="co"># setting the theme for plotting</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'#1A090D'</span>, <span class="st">'#D8C99B'</span>, <span class="st">'#D8973C'</span>, <span class="st">'#BD632F'</span>, <span class="st">'#273E47'</span>]</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>cmap <span class="op">=</span> mcolors.ListedColormap(colors)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>font <span class="op">=</span> FontProperties()</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>font.set_family(<span class="st">'avenir'</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>font.set_name(<span class="st">'Avenir'</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>font.set_style(<span class="st">'normal'</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>font.set_size(<span class="st">'xx-large'</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing custom libraries</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ----------------------------</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>sys.path.insert(<span class="dv">0</span>,<span class="st">'../src/'</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ZTF_data <span class="im">import</span> <span class="op">*</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> config <span class="im">import</span><span class="op">*</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> descriptive_stats <span class="im">import</span> <span class="op">*</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plots <span class="im">import</span> <span class="op">*</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Loading the data!</code></pre>
</div>
</div>
</section>
<section id="downloading-linear-and-ztf-data" class="level1">
<h1>Downloading <code>LINEAR</code> and <code>ZTF</code> data</h1>
<section id="linear-dataset" class="level2">
<h2 class="anchored" data-anchor-id="linear-dataset"><code>LINEAR</code> dataset</h2>
<p>The <code>LINEAR dataset</code> <em>(Lincon Near-Earth Asteroid Research)</em> contains 7010 light curves of periodic variable stars. While the original mission of this survey was to find asteroids, it subsequently monitored a substantial portion of the sky, cataloging the brightness of various variable stars. This survey was operated with two telescopes on a site in New Mexico. The two telescopes are equatorially mounted of GEODSS type, where each telescope is denoted as L1 and L2. They observed a broad part of the visible spectrum and the near-infrared spectrum.</p>
<p>The preprocessing process contained the following procedures: 1. <strong>Bias correction</strong>: removing noise created by the camera 2. <strong>Flat-field correction</strong>: removing artificial lines and gradients due to varying sensitivities of pixels 3. <strong>Preliminary fixed-aperture photometry</strong>: subtracting the background light using Poisson statistics</p>
<p>After preprocessing, the data had to be astrometrically recalibrated, meaning that the scientists had to ensure the coordinates of the objects in the data matched another survey, like SDSS. Of all the data, 7% had bad astrometry (the coordinates did not fit), so the scientists removed them from the dataset. The rest of the data had a 1-2% error in astrometry.</p>
<p>Next up was photometric recalibration, meaning that the filters and fluxes had to be recalibrated to match SDSS data. The corrections regarded CCD camera errors, correcting the magnitudes of objects in the data, and correcting underestimated magnitude errors. After the photometric recalibration, the data were grouped into various categories, including a variable star category. While the original dataset has 5 billion objects, <em>only 7010 are confirmed periodic variable stars</em>. The scientists subsequently analyzed this portion of the dataset by categorizing the light curves, calculating their periods, and inferring conclusions from the preceding factors.</p>
<p>We can access the <code>LINEAR</code> dataset via one line of code since we are downloading the data from the AstroML library.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># LINEAR DATA</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>dataL <span class="op">=</span> fetch_LINEAR_sample(data_home<span class="op">=</span><span class="st">'../inputs'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="7">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># acessing all of the light curves from the dataL and checking if any light curve is missing</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>c <span class="op">=</span> <span class="dv">0</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> dataL.ids: <span class="co"># iterating through all of the dataL ID's</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    light_curve <span class="op">=</span> dataL.get_light_curve(i) <span class="co"># fetching the light curve dataL for a specific ID</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    c <span class="op">+=</span> <span class="dv">1</span> </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'The number of light curves in the LINEAR dataset:</span><span class="sc">{</span>c<span class="sc">}</span><span class="ss">'</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The number of light curves in the LINEAR dataset:7010</code></pre>
</div>
</div>
<p>The counter has printed the number <code>7010</code>, the correct amount of light curves in this dataset. No light curves are missing!</p>
<section id="structure-of-linear-dataset" class="level4">
<h4 class="anchored" data-anchor-id="structure-of-linear-dataset">Structure of <code>LINEAR</code> dataset</h4>
<p>The structure of the <code>LINEAR</code> dataset is as such: 1. <code>dataL</code> is a <code>AstroML.datasets</code> object and it contains the following:</p>
<p>1.a) <code>dataL.ids</code> is a list of all the IDs of the stars</p>
<p>1.b) <code>dataL.get_light_curve()</code> is a function which acceses the data for a specific ID of a light curve every light curve is a <code>np.array()</code> object where every column is <code>time</code>, <code>magnitude</code> and the <code>magnitude error</code>. In order to get an array for every column the original array must be transposed.</p>
<ol start="2" type="1">
<li><code>dataL.targets</code> contains all of the metadata for every light curve eg. rectascension, declination, etc.</li>
</ol>
<p>Here is an example of a light curve:</p>
<div class="cell" data-execution_count="7">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>ID <span class="op">=</span> dataL.ids[<span class="dv">0</span>] <span class="co"># accessing the first LINEAR ID</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>lc <span class="op">=</span> dataL.get_light_curve(ID)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>time, mag, magerr <span class="op">=</span> lc.T <span class="co"># transposing the data</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">#--------</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'LINEAR ID:</span><span class="sc">{</span>ID<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>targets <span class="op">=</span> dataL.targets[<span class="dv">0</span>]</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(targets)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>ra, dec <span class="op">=</span> targets[<span class="dv">3</span>], targets[<span class="dv">4</span>]</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Rectascension:</span><span class="sc">{</span>ra<span class="sc">}</span><span class="ss">, and Declination:</span><span class="sc">{</span>dec<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co">#--------</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">9</span>)) <span class="co"># creating subplots with 2 columms and 3 rows</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>ax.errorbar(time, mag, magerr, fmt<span class="op">=</span><span class="st">'.k'</span>, ecolor<span class="op">=</span><span class="st">'gray'</span>,lw<span class="op">=</span><span class="dv">1</span>, ms<span class="op">=</span><span class="dv">4</span>, capsize<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Time (days)'</span>,fontproperties<span class="op">=</span>font)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Magnitude'</span>, fontproperties<span class="op">=</span>font)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'LINEAR object </span><span class="sc">{0}</span><span class="st">'</span>.<span class="bu">format</span>(ID), fontproperties<span class="op">=</span>font)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>ax.invert_yaxis()</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>LINEAR ID:10003298
(10003298, 207.52946, 33.70615, 207.529404, 33.706001, 15.73, 1.84, 0.81, 0.31, 0.16, 0.63, 15.89, 0.16, 0.19, 1.12, -0.61, -0.01, -1, 0)
Rectascension:207.529404, and Declination:33.706001</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/figure-html/cell-7-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>For further analysis we will require the <code>LINEAR ID</code>, the <code>ra</code> and <code>dec</code> values, and finally, the data for every light curve (time, magnitude, errors).</p>
</section>
<section id="introductory-statistics-of-linear-data" class="level3">
<h3 class="anchored" data-anchor-id="introductory-statistics-of-linear-data">Introductory statistics of <code>LINEAR</code> data</h3>
<div class="cell" data-execution_count="8">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># NUMBER OF MEASUREMENTS</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------------</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>pL <span class="op">=</span> []</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> dataL.ids:</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    lc <span class="op">=</span> dataL.get_light_curve(i)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    t, m, me <span class="op">=</span> lc.T</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    pL.append(<span class="bu">len</span>(t))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>total_obser <span class="op">=</span> <span class="bu">sum</span>(pL) <span class="co"># summing the number of measurements of every light curve</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Our dataset contains </span><span class="sc">{</span>total_obser<span class="sc">}</span><span class="ss"> observations!'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Our dataset contains 1851936 observations!</code></pre>
</div>
</div>
<div class="cell" data-execution_count="9">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">9</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>pL,color<span class="op">=</span><span class="st">'#BD632F'</span>) <span class="co"># drawing a histogram of the distribution of measurements</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of measurements'</span>, fontproperties<span class="op">=</span>font)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Periods of measurements'</span>, fontproperties<span class="op">=</span>font)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Count'</span>, fontproperties<span class="op">=</span>font)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/figure-html/cell-9-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The graph above shows that most of our light curves have around 200 to 300 measurements, with a subsequent peak at about 500 measurements per light curve.</p>
<div class="cell" data-execution_count="11">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># TIME DIFFERENCE</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>tmL <span class="op">=</span> []</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> dataL.ids:</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    lightc <span class="op">=</span> dataL.get_light_curve(i)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    t, m, me <span class="op">=</span> lightc.T</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    time <span class="op">=</span> t[<span class="bu">len</span>(t)<span class="op">-</span><span class="dv">1</span>] <span class="op">-</span> t[<span class="dv">0</span>] <span class="co"># last time - first time</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    tmL.append(time)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="10">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">9</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>tmL,color<span class="op">=</span><span class="st">'#D8973C'</span>, bins<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of time periods'</span>,fontproperties<span class="op">=</span>font)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Time intervals'</span>,fontproperties<span class="op">=</span>font)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Count'</span>, fontproperties<span class="op">=</span>font)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/figure-html/cell-11-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>This graph shows that most of our time intervals span around 1800 to 2000 days. So, no matter the variable star type, most actual time intervals are very long.</p>
</section>
</section>
<section id="ztf-dataset" class="level2">
<h2 class="anchored" data-anchor-id="ztf-dataset"><code>ZTF</code> dataset</h2>
<p>The <code>Zwicky Transient Facility</code> is an optical time-domain survey that uses the Palomar 48-inch Schmidt telescope to observe the entire Northern hemisphere sky in 3 different bands: <code>g,</code> <code>r</code>, and <code>i</code>, and has been operating since October 2017. This telescope has a large field of view, taking in a lot of data.</p>
<p>All the data gathered by <code>ZTF</code> is stored at the IPAC, which can be accessed via IRSA, as shown in this project. All of the raw data was processed so that every pixel had an average of 5 bits, and although this increased sky noise by 1%, the increase is negligible. All the images were FITS images which the program processed in the following way:</p>
<ol type="1">
<li><p><strong>Preprocessing:</strong> removing bias frames and flat field correction frames.</p></li>
<li><p><strong>Astrometry:</strong> Using the <code>SCAMP</code> package, all objects were astrometrically calibrated to match the <code>GAIA</code> survey.</p></li>
<li><p><strong>Photometry:</strong> All images were photometrically calibrated following the <code>PanSTARRS 1</code> survey.</p></li>
<li><p><strong>Final processing:</strong> Finally, masks were made for saturation, bad pixels were removed, ghosts and any instrumental artifacts, and other defects.</p></li>
</ol>
<p>Every image was then categorized as either a moving or a changing source using the <code>ZOGY</code> algorithm. Furthermore, point-like moving objects were identified using the custom <code>ZTF Moving-object Discovery Engine (ZMODE).</code></p>
<p><code>ZTF</code> was able to observe the following objects:</p>
<p><strong>1. Transient objects</strong></p>
<p>These objects are supernovae found in other galaxies, and the <code>ZTF</code> survey captured their light curves.</p>
<p><strong>2. Neutrinos and gravitational-wave events</strong></p>
<p>The <code>ZTF</code> survey showed that scientists could use <code>ZTF</code> in the future to undertake observations of neutrinos and gravitational-wave events.</p>
<p><strong>3. Variable objects</strong></p>
<p>These include variable stars but also light curves of asteroids. The light curves in the <code>ZTF</code>dataset were built upon every few months, and the light curves were stored in <code>HDF5</code> match files per each field of observation. <code>ZTF</code> contains many light curves, and some most notable types are <em>Be stars</em>, <em>RR Lyrae</em> stars, light curves of <em>NEOs</em>, <em>Asteroids</em>, and the activity of <em>Comets and Centaurs</em>.</p>
<section id="accessing-the-ztf-data" class="level3">
<h3 class="anchored" data-anchor-id="accessing-the-ztf-data">Accessing the <code>ZTF</code> data</h3>
<p>The <code>ZTF</code> data is on an extrenal API provided by the <code>IRSA</code> webpage. Since querying for the data takes a lot of time, we use <strong>asynchronous</strong> programming to tackle multiple queries at a time, significantly shortening the runtime. All light curves are searched by equatorial coordinates (found in <code>dataL.targets</code>) and saved as <code>DataFrames</code> inside an array, along with the search ID as a <code>tuple</code>. So, <em>array([(ID1, DataFrame object 1), (ID2, DataFrame object 2),…])</em>. All of the code can be found in the custom <code>ZTF_data.py</code> library.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>ZTF_data <span class="op">=</span> data_ztf(<span class="st">'ZTF_light_curves.npy'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accessing the data!</code></pre>
</div>
</div>
<div class="cell" data-execution_count="13">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Shape of the dataset:'</span>, ZTF_data[<span class="dv">0</span>][<span class="dv">1</span>].shape)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ZTF_data[<span class="dv">0</span>][<span class="dv">1</span>].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(2197, 4)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="13">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>mjd</th>
      <th>mag</th>
      <th>magerr</th>
      <th>filtercode</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>58202.353634</td>
      <td>16.516510</td>
      <td>0.016864</td>
      <td>zg</td>
    </tr>
    <tr>
      <th>1</th>
      <td>58202.357454</td>
      <td>16.517498</td>
      <td>0.016866</td>
      <td>zg</td>
    </tr>
    <tr>
      <th>2</th>
      <td>58205.341262</td>
      <td>16.568840</td>
      <td>0.017013</td>
      <td>zg</td>
    </tr>
    <tr>
      <th>3</th>
      <td>58205.392616</td>
      <td>17.055435</td>
      <td>0.019523</td>
      <td>zg</td>
    </tr>
    <tr>
      <th>4</th>
      <td>58208.322326</td>
      <td>16.585726</td>
      <td>0.017066</td>
      <td>zg</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>The ZTF data is structured so every light curve has an ID or the order it was processed in as the first element of a <code>tuple</code>, and the second element is a <code>Pandas DataFrame</code>, which contains the light curve data. It has 4 columns: <code>mjd</code> or the time values, <code>mag</code> or the magnitude values, <code>magerr</code> or the magnitude errors, and finally <code>filtercode</code> or the filter in which the data was taken in.</p>
<p>Every light curve was made in 3 filters: <code>zg</code>, <code>zr</code> and <code>zi</code>, or the green, red and infrared filters. Each filter has a different amount of observation points and gives us insight into the light curve’s structure.</p>
<div class="cell" data-execution_count="14">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>no <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>na_id <span class="op">=</span> []</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(NUM_STARS):</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> ZTF_data[i][<span class="dv">1</span>].empty <span class="op">==</span> <span class="va">True</span>: <span class="co"># if the dataframe is empty,</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>        no <span class="op">+=</span> <span class="dv">1</span> <span class="co"># count it</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>        na_id.append(i)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Number of empty light curve DataFrames'</span>, no)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>178
[21, 43, 48, 64, 75, 119, 138, 151, 165, 180]</code></pre>
</div>
</div>
<p>We can see that 178 light curves in the ZTF datasets contain no values, meaning they were not found in the ZTF database.</p>
<div class="cell" data-execution_count="15">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># NUMBER OF OBSERVATIONS</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------------------</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>pztf <span class="op">=</span> []</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> num:</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    pztf.append(ZTF_data[i][<span class="dv">1</span>].shape[<span class="dv">0</span>])</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>total_obser_ztf <span class="op">=</span> <span class="bu">sum</span>(pztf) <span class="co"># summing the number of observation for every light curve</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>9187878</code></pre>
</div>
</div>
<p>The ZTF data contains 9 187 878 observations! That is almost nine times more than for the LINEAR data.</p>
<div class="cell" data-execution_count="16">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">9</span>))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>pztf,color<span class="op">=</span><span class="st">'#BD632F'</span>) <span class="co"># drawing a histogram of the distribution of measurements</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of measurements'</span>, fontproperties<span class="op">=</span>font)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Periods of measurements'</span>, fontproperties<span class="op">=</span>font)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Count'</span>, fontproperties<span class="op">=</span>font)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/figure-html/cell-16-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The graph above shows that a considerable amount of light curves contain very few points in their observation, with another peak at around 1000 observations.</p>
</section>
<section id="splitting-the-data-into-respective-filters-for-analysis" class="level3">
<h3 class="anchored" data-anchor-id="splitting-the-data-into-respective-filters-for-analysis">Splitting the data into respective filters for analysis</h3>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>ZTF_g <span class="op">=</span> []</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>ZTF_r <span class="op">=</span> []</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>ZTF_i <span class="op">=</span> []</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> tqdm(<span class="bu">range</span>(NUM_STARS)):</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    lc <span class="op">=</span> ZTF_data[i][<span class="dv">1</span>]</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># green</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    lcg <span class="op">=</span> lc.loc[lc[<span class="st">'filtercode'</span>]<span class="op">==</span><span class="st">'zg'</span>]</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    lcg <span class="op">=</span> lcg.reset_index()</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    lcg <span class="op">=</span> lcg.drop([<span class="st">'index'</span>],axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>    ZTF_g.append((i, lcg))</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># red</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    lcr <span class="op">=</span> lc.loc[lc[<span class="st">'filtercode'</span>]<span class="op">==</span><span class="st">'zr'</span>]</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    lcr <span class="op">=</span> lcr.reset_index()</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    lcr <span class="op">=</span> lcr.drop([<span class="st">'index'</span>],axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    ZTF_r.append((i, lcr))</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># infrared</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>    lci <span class="op">=</span> lc.loc[lc[<span class="st">'filtercode'</span>]<span class="op">==</span><span class="st">'zi'</span>]</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>    lci <span class="op">=</span> lci.reset_index()</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>    lci <span class="op">=</span> lci.drop([<span class="st">'index'</span>],axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>    ZTF_i.append((i, lci))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>100%|██████████| 7010/7010 [00:26&lt;00:00, 267.98it/s]</code></pre>
</div>
</div>
<p>Now we have separated every star by its filter! We now have 3 respective datasets of the same stars where each dataframe encompases the filters of every light curve.</p>
</section>
<section id="introductory-statistics-on-ztf-data" class="level3">
<h3 class="anchored" data-anchor-id="introductory-statistics-on-ztf-data">Introductory statistics on <code>ZTF</code> data</h3>
<div class="cell" data-execution_count="24">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># TIME DIFFERENCE</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ----------------</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>time_g <span class="op">=</span> []</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>time_r <span class="op">=</span> []</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>time_i <span class="op">=</span> []</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> tqdm(<span class="bu">range</span>(NUM_STARS)):</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    lcg <span class="op">=</span> ZTF_g[i][<span class="dv">1</span>]</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    lcr <span class="op">=</span> ZTF_r[i][<span class="dv">1</span>]</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    lci <span class="op">=</span> ZTF_i[i][<span class="dv">1</span>]</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># green</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> lcg.shape[<span class="dv">0</span>] <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>        n <span class="op">=</span> lcg.shape[<span class="dv">0</span>]<span class="op">-</span><span class="dv">1</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>        timeg <span class="op">=</span> lcg[<span class="st">'mjd'</span>][n] <span class="op">-</span> lcg[<span class="st">'mjd'</span>][<span class="dv">0</span>]</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>        time_g.append(timeg)</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">pass</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># red</span></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> lcr.shape[<span class="dv">0</span>] <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>        n <span class="op">=</span> lcr.shape[<span class="dv">0</span>]<span class="op">-</span><span class="dv">1</span></span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>        timer <span class="op">=</span> lcr[<span class="st">'mjd'</span>][n] <span class="op">-</span> lcr[<span class="st">'mjd'</span>][<span class="dv">0</span>]</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>        time_r.append(timer)</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a>        <span class="cf">pass</span></span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>    <span class="co"># infrared</span></span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> lci.shape[<span class="dv">0</span>] <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a>        n <span class="op">=</span> lci.shape[<span class="dv">0</span>]<span class="op">-</span><span class="dv">1</span></span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a>        timei <span class="op">=</span> lci[<span class="st">'mjd'</span>][n] <span class="op">-</span> lci[<span class="st">'mjd'</span>][<span class="dv">0</span>]</span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a>        time_i.append(timei)</span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb26-35"><a href="#cb26-35" aria-hidden="true" tabindex="-1"></a>        <span class="cf">pass</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>100%|██████████| 7010/7010 [00:01&lt;00:00, 3695.43it/s]</code></pre>
</div>
</div>
<div class="cell" data-execution_count="25">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PLOTTING TIME DIFFERENCE</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># -------------------------</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">30</span>,<span class="dv">10</span>))</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram 1</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].set_title(<span class="st">'Timespan histogram of filter G'</span>,fontproperties<span class="op">=</span>font)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>time_g,color<span class="op">=</span><span class="st">'#D8C99B'</span>,ax<span class="op">=</span>axs[<span class="dv">0</span>]) <span class="co"># drawing a histogram of the distribution of measurements</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="co">#histogram 2</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>].set_title(<span class="st">'Timespan histogram of filter R'</span>,fontproperties<span class="op">=</span>font)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>time_r,color<span class="op">=</span><span class="st">'#D8973C'</span>,ax<span class="op">=</span>axs[<span class="dv">1</span>]) <span class="co"># drawing a histogram of the distribution of measurements</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="co">#histogram 3</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">2</span>].set_title(<span class="st">'Timespan histogram of filter I'</span>,fontproperties<span class="op">=</span>font)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>time_i,color<span class="op">=</span><span class="st">'#BD632F'</span>,ax<span class="op">=</span>axs[<span class="dv">2</span>]) <span class="co"># drawing a histogram of the distribution of measurements</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/figure-html/cell-19-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>In the <code>g</code> filter, most timespans are of 1750 days, with a subsequent peak at around 1100 days. In the <code>r</code> filter we can see a similar distribution, although the peak at aroun 1100 is much stronger. Finally, in the <code>i</code> filter, most timespans are around 1300 days, with a subsequent peak at around 400! This is the shortest inerval thus far.</p>
</section>
</section>
</section>
<section id="analysis-of-linear-and-ztf-data" class="level1">
<h1>Analysis of <code>LINEAR</code> and <code>ZTF</code> data</h1>
<section id="descriptive-statistics-of-magnitude-values" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics-of-magnitude-values">Descriptive statistics of magnitude values</h2>
<section id="linear-dataset-1" class="level5">
<h5 class="anchored" data-anchor-id="linear-dataset-1"><code>LINEAR</code> dataset</h5>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>stats_L <span class="op">=</span> lc_descriptive_stats_table_LINEAR(<span class="st">'mag'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Argument received: mag</code></pre>
</div>
</div>
<div class="cell" data-execution_count="27">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>stats_L.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="27">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>mean</th>
      <th>median</th>
      <th>std</th>
      <th>amin</th>
      <th>amax</th>
      <th>skew</th>
      <th>kurtosis</th>
      <th>Amplitude</th>
    </tr>
    <tr>
      <th>index</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>10003298</th>
      <td>15.920224</td>
      <td>15.8880</td>
      <td>0.159858</td>
      <td>15.679</td>
      <td>16.360</td>
      <td>0.659768</td>
      <td>-0.482567</td>
      <td>0.681</td>
    </tr>
    <tr>
      <th>10004892</th>
      <td>16.839543</td>
      <td>16.8440</td>
      <td>0.236847</td>
      <td>16.382</td>
      <td>17.975</td>
      <td>0.767109</td>
      <td>3.528837</td>
      <td>1.593</td>
    </tr>
    <tr>
      <th>10013411</th>
      <td>15.574235</td>
      <td>15.5020</td>
      <td>0.192148</td>
      <td>15.400</td>
      <td>16.391</td>
      <td>2.227095</td>
      <td>4.286783</td>
      <td>0.991</td>
    </tr>
    <tr>
      <th>10021274</th>
      <td>14.939383</td>
      <td>14.9885</td>
      <td>0.231373</td>
      <td>14.289</td>
      <td>15.330</td>
      <td>-0.624265</td>
      <td>-0.566168</td>
      <td>1.041</td>
    </tr>
    <tr>
      <th>10022663</th>
      <td>14.253744</td>
      <td>14.2935</td>
      <td>0.227889</td>
      <td>13.698</td>
      <td>14.665</td>
      <td>-0.550420</td>
      <td>-0.498097</td>
      <td>0.967</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
<section id="ztf-dataset-1" class="level4">
<h4 class="anchored" data-anchor-id="ztf-dataset-1"><code>ZTF</code> dataset</h4>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>stats_Z_g <span class="op">=</span> lc_descriptive_stats_table_ZTF(<span class="st">'mag'</span>, ZTF_g)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="29">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>stats_Z_g.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="29">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>mean</th>
      <th>median</th>
      <th>std</th>
      <th>amin</th>
      <th>amax</th>
      <th>skew</th>
      <th>kurtosis</th>
      <th>Amplitude</th>
    </tr>
    <tr>
      <th>index</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>mag</th>
      <td>16.735973</td>
      <td>16.682770</td>
      <td>0.190980</td>
      <td>16.355003</td>
      <td>17.274315</td>
      <td>0.547621</td>
      <td>-0.987585</td>
      <td>0.919311</td>
    </tr>
    <tr>
      <th>mag</th>
      <td>17.090297</td>
      <td>17.166143</td>
      <td>0.248268</td>
      <td>16.568600</td>
      <td>17.351080</td>
      <td>-1.005061</td>
      <td>-0.432566</td>
      <td>0.782480</td>
    </tr>
    <tr>
      <th>mag</th>
      <td>16.204822</td>
      <td>16.146278</td>
      <td>0.152526</td>
      <td>15.931999</td>
      <td>16.806747</td>
      <td>2.009203</td>
      <td>3.217131</td>
      <td>0.874748</td>
    </tr>
    <tr>
      <th>mag</th>
      <td>15.013304</td>
      <td>15.165165</td>
      <td>0.365250</td>
      <td>14.104170</td>
      <td>15.602118</td>
      <td>-0.741975</td>
      <td>-0.814440</td>
      <td>1.497949</td>
    </tr>
    <tr>
      <th>mag</th>
      <td>14.372281</td>
      <td>14.500145</td>
      <td>0.362280</td>
      <td>13.489013</td>
      <td>15.489503</td>
      <td>-0.676807</td>
      <td>-0.701880</td>
      <td>2.000490</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>stats_Z_r <span class="op">=</span> lc_descriptive_stats_table_ZTF(<span class="st">'mag'</span>, ZTF_r)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="31">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>stats_Z_r.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="31">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>mean</th>
      <th>median</th>
      <th>std</th>
      <th>amin</th>
      <th>amax</th>
      <th>skew</th>
      <th>kurtosis</th>
      <th>Amplitude</th>
    </tr>
    <tr>
      <th>index</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>mag</th>
      <td>15.897570</td>
      <td>15.851342</td>
      <td>0.167484</td>
      <td>15.633669</td>
      <td>16.323614</td>
      <td>0.522559</td>
      <td>-1.009893</td>
      <td>0.689945</td>
    </tr>
    <tr>
      <th>mag</th>
      <td>16.785922</td>
      <td>16.774748</td>
      <td>0.220514</td>
      <td>16.429140</td>
      <td>17.081219</td>
      <td>-0.150690</td>
      <td>-1.395480</td>
      <td>0.652079</td>
    </tr>
    <tr>
      <th>mag</th>
      <td>15.458849</td>
      <td>15.393452</td>
      <td>0.165171</td>
      <td>15.277586</td>
      <td>16.366425</td>
      <td>2.121737</td>
      <td>3.979763</td>
      <td>1.088839</td>
    </tr>
    <tr>
      <th>mag</th>
      <td>14.851248</td>
      <td>14.929792</td>
      <td>0.255162</td>
      <td>13.541904</td>
      <td>15.399588</td>
      <td>-0.686116</td>
      <td>-0.339955</td>
      <td>1.857683</td>
    </tr>
    <tr>
      <th>mag</th>
      <td>14.196490</td>
      <td>14.250234</td>
      <td>0.245730</td>
      <td>13.636862</td>
      <td>14.918344</td>
      <td>-0.551952</td>
      <td>-0.699978</td>
      <td>1.281482</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>stats_Z_i <span class="op">=</span> lc_descriptive_stats_table_ZTF(<span class="st">'mag'</span>, ZTF_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="33">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>stats_Z_i.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="33">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>mean</th>
      <th>median</th>
      <th>std</th>
      <th>amin</th>
      <th>amax</th>
      <th>skew</th>
      <th>kurtosis</th>
      <th>Amplitude</th>
    </tr>
    <tr>
      <th>index</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>mag</th>
      <td>15.600686</td>
      <td>15.549002</td>
      <td>0.168734</td>
      <td>15.294890</td>
      <td>15.917844</td>
      <td>0.405756</td>
      <td>-1.221085</td>
      <td>0.622954</td>
    </tr>
    <tr>
      <th>mag</th>
      <td>15.128821</td>
      <td>15.077989</td>
      <td>0.133336</td>
      <td>15.009691</td>
      <td>15.657438</td>
      <td>2.311716</td>
      <td>4.382408</td>
      <td>0.647747</td>
    </tr>
    <tr>
      <th>mag</th>
      <td>14.868257</td>
      <td>14.941725</td>
      <td>0.199451</td>
      <td>14.308695</td>
      <td>15.290393</td>
      <td>-0.604343</td>
      <td>-0.736272</td>
      <td>0.981698</td>
    </tr>
    <tr>
      <th>mag</th>
      <td>15.700998</td>
      <td>15.610683</td>
      <td>0.229866</td>
      <td>15.428493</td>
      <td>16.695438</td>
      <td>1.166536</td>
      <td>0.739817</td>
      <td>1.266946</td>
    </tr>
    <tr>
      <th>mag</th>
      <td>15.767120</td>
      <td>15.766270</td>
      <td>0.028933</td>
      <td>15.552393</td>
      <td>15.897695</td>
      <td>-1.391850</td>
      <td>16.485549</td>
      <td>0.345302</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<section id="plotting-the-results" class="level5">
<h5 class="anchored" data-anchor-id="plotting-the-results">Plotting the results</h5>
<p>We need to reset all the indexes so that the results can be plotted!</p>
<div class="cell" data-execution_count="39">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>stats_Z_g <span class="op">=</span> stats_Z_g.reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>stats_Z_r <span class="op">=</span> stats_Z_r.reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>stats_Z_i <span class="op">=</span> stats_Z_i.reset_index(drop<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>True
True
True
True</code></pre>
</div>
</div>
<div class="cell" data-execution_count="44">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>columns <span class="op">=</span> [<span class="st">'mean'</span>, <span class="st">'median'</span>, <span class="st">'std'</span>, <span class="st">'amin'</span>, <span class="st">'amax'</span>, <span class="st">'skew'</span>,<span class="st">'kurtosis'</span>,<span class="st">'Amplitude'</span>]</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">4</span>,<span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">30</span>,<span class="dv">18</span>)) <span class="co"># creating subplots with 2 columms and 3 rows</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> ax.flatten() <span class="co"># flatten the axes</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> tqdm(<span class="bu">range</span>(<span class="bu">len</span>(columns))): <span class="co">#plot the same type of graph for every property</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    ax[i].set_title(columns[i].upper(), fontproperties<span class="op">=</span>font) <span class="co"># the title of the graph is the column name</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    sns.histplot(data<span class="op">=</span>stats_L,x<span class="op">=</span>columns[i],ax<span class="op">=</span>ax[i], color<span class="op">=</span><span class="st">'#273E47'</span>, alpha<span class="op">=</span><span class="fl">0.3</span>) <span class="co"># blue</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>    sns.histplot(data<span class="op">=</span>stats_Z_g, x<span class="op">=</span>columns[i], ax<span class="op">=</span>ax[i], color<span class="op">=</span><span class="st">'#D8C99B'</span>,alpha<span class="op">=</span><span class="fl">0.3</span>) <span class="co"># light color</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>    sns.histplot(data<span class="op">=</span>stats_Z_r, x<span class="op">=</span>columns[i], ax<span class="op">=</span>ax[i], color<span class="op">=</span><span class="st">'#D8973C'</span>,alpha<span class="op">=</span><span class="fl">0.3</span>) <span class="co"># orange color</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>    sns.histplot(data<span class="op">=</span>stats_Z_i, x<span class="op">=</span>columns[i], ax<span class="op">=</span>ax[i], color<span class="op">=</span><span class="st">'#BD632F'</span>,alpha<span class="op">=</span><span class="fl">0.3</span>) <span class="co"># dark orange color</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>100%|██████████| 8/8 [00:13&lt;00:00,  1.74s/it]</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/figure-html/cell-29-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>From the graphs above we can make a few conclusions.</p>
<ol type="1">
<li><p><strong>The mean graph</strong>: the distribution from all the data is more or less the same, and the most common mean is from 16 to 17 magnitudes. The most visible difference is how the green filter of the <code>ZTF</code> data has a longer tail towards lower magnitudes, while the infrared filter has a longer tail towards the higher magnitudes.</p></li>
<li><p><strong>The median graphs</strong>: the distribution from all the data is kind of the same, where the most common median is around 16 magnitudes. The observation from the mean graph also applies here.</p></li>
<li><p><strong>The standard deviation graph</strong>: Here we can see large discrepancies. There are 2 peaks: one peak is at around 0 (meaning the data is very concentrated), and another peak is at around 0.2 (which is also very concentrated around the mean). The <code>ZTF</code> green filter has a distribution where many values are inbetween 0.2 and 0.4. The <code>LINEAR</code> dataset doesn’t have a peak at around 0.</p></li>
<li><p><strong>The minimum graph</strong>: Here the distributions are almost identical, and most minimums range at around 16 magnitudes. The <code>ZTF</code> green filter has a distribution ranging all the way to 18 magnitudes.</p></li>
<li><p><strong>The maximum graph</strong>: Again, the distribution is almost identical, where values range from 14 magnitudes to 20 magnitudes.</p></li>
<li><p><strong>The skew graph</strong>: All the distributions are almost identical, and most values range around 0, meaning that the distributions aren’t very skewed.</p></li>
<li><p><strong>The kurtosis graph</strong>: again, the distributions are almost identical, and almost every value is around 0, meaning that most of our light curves follow a normal distribution.</p></li>
<li><p><strong>The amplitude graph</strong>: Here the distributions aren’t so similar. The most common <code>LINEAR</code> amplitude is a bit less than 1 magnitude, for <code>ZTF</code> green data is around 1.5, for <code>ZTF</code> red is around 1-1.1 magnitudes, and finally for <code>ZTF</code> infrared the most common amplitude is around 0.6-0.7 magnitudes. The total range is from close to 0 all the way to 4 magnitudes!</p></li>
</ol>
</section>
</section>
</section>
<section id="descriptive-statistics-of-magnitude-error-values" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics-of-magnitude-error-values">Descriptive statistics of magnitude error values</h2>
<section id="linear-data" class="level4">
<h4 class="anchored" data-anchor-id="linear-data"><code>LINEAR</code> data</h4>
<div class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>stats_L_er <span class="op">=</span> lc_descriptive_stats_table_LINEAR(<span class="st">'magerr'</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>stats_L_er.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Argument received: magerr</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="46">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>mean</th>
      <th>median</th>
      <th>std</th>
      <th>amin</th>
      <th>amax</th>
      <th>skew</th>
      <th>kurtosis</th>
      <th>Amplitude</th>
    </tr>
    <tr>
      <th>index</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>10003298</th>
      <td>0.048587</td>
      <td>0.044</td>
      <td>0.018496</td>
      <td>0.018</td>
      <td>0.115</td>
      <td>1.239252</td>
      <td>1.627132</td>
      <td>0.097</td>
    </tr>
    <tr>
      <th>10004892</th>
      <td>0.109491</td>
      <td>0.098</td>
      <td>0.053818</td>
      <td>0.039</td>
      <td>0.332</td>
      <td>1.606721</td>
      <td>3.142803</td>
      <td>0.293</td>
    </tr>
    <tr>
      <th>10013411</th>
      <td>0.039447</td>
      <td>0.028</td>
      <td>0.042827</td>
      <td>0.015</td>
      <td>0.448</td>
      <td>6.871714</td>
      <td>56.888840</td>
      <td>0.433</td>
    </tr>
    <tr>
      <th>10021274</th>
      <td>0.020528</td>
      <td>0.020</td>
      <td>0.009136</td>
      <td>0.009</td>
      <td>0.056</td>
      <td>1.671405</td>
      <td>3.435779</td>
      <td>0.047</td>
    </tr>
    <tr>
      <th>10022663</th>
      <td>0.012114</td>
      <td>0.011</td>
      <td>0.005738</td>
      <td>0.006</td>
      <td>0.043</td>
      <td>2.365310</td>
      <td>8.099770</td>
      <td>0.037</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
<section id="ztf-data" class="level4">
<h4 class="anchored" data-anchor-id="ztf-data"><code>ZTF</code> data</h4>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>stats_Z_g_er <span class="op">=</span> lc_descriptive_stats_table_ZTF(<span class="st">'magerr'</span>, ZTF_g)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>stats_Z_g_er.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="47">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>mean</th>
      <th>median</th>
      <th>std</th>
      <th>amin</th>
      <th>amax</th>
      <th>skew</th>
      <th>kurtosis</th>
      <th>Amplitude</th>
    </tr>
    <tr>
      <th>index</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>magerr</th>
      <td>0.016739</td>
      <td>0.016988</td>
      <td>0.001702</td>
      <td>0.013247</td>
      <td>0.021473</td>
      <td>-0.194755</td>
      <td>-0.749422</td>
      <td>0.008226</td>
    </tr>
    <tr>
      <th>magerr</th>
      <td>0.019975</td>
      <td>0.020332</td>
      <td>0.001545</td>
      <td>0.016999</td>
      <td>0.021836</td>
      <td>-0.792410</td>
      <td>-0.726045</td>
      <td>0.004837</td>
    </tr>
    <tr>
      <th>magerr</th>
      <td>0.014782</td>
      <td>0.014636</td>
      <td>0.000557</td>
      <td>0.013328</td>
      <td>0.017227</td>
      <td>1.396176</td>
      <td>4.349406</td>
      <td>0.003898</td>
    </tr>
    <tr>
      <th>magerr</th>
      <td>0.013280</td>
      <td>0.013297</td>
      <td>0.000231</td>
      <td>0.011187</td>
      <td>0.013583</td>
      <td>-7.032957</td>
      <td>54.219491</td>
      <td>0.002396</td>
    </tr>
    <tr>
      <th>magerr</th>
      <td>0.014277</td>
      <td>0.014225</td>
      <td>0.000269</td>
      <td>0.012926</td>
      <td>0.014828</td>
      <td>-2.337813</td>
      <td>10.403696</td>
      <td>0.001902</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>stats_Z_r_er <span class="op">=</span> lc_descriptive_stats_table_ZTF(<span class="st">'magerr'</span>, ZTF_r)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>stats_Z_r_er.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="48">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>mean</th>
      <th>median</th>
      <th>std</th>
      <th>amin</th>
      <th>amax</th>
      <th>skew</th>
      <th>kurtosis</th>
      <th>Amplitude</th>
    </tr>
    <tr>
      <th>index</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>magerr</th>
      <td>0.014733</td>
      <td>0.014637</td>
      <td>0.000322</td>
      <td>0.013360</td>
      <td>0.015830</td>
      <td>-0.113479</td>
      <td>3.489046</td>
      <td>0.002469</td>
    </tr>
    <tr>
      <th>magerr</th>
      <td>0.016733</td>
      <td>0.016517</td>
      <td>0.001295</td>
      <td>0.014859</td>
      <td>0.018631</td>
      <td>0.055509</td>
      <td>-1.437554</td>
      <td>0.003772</td>
    </tr>
    <tr>
      <th>magerr</th>
      <td>0.013516</td>
      <td>0.013459</td>
      <td>0.000139</td>
      <td>0.013451</td>
      <td>0.014983</td>
      <td>3.855843</td>
      <td>23.218715</td>
      <td>0.001532</td>
    </tr>
    <tr>
      <th>magerr</th>
      <td>0.014877</td>
      <td>0.014798</td>
      <td>0.000269</td>
      <td>0.013531</td>
      <td>0.015498</td>
      <td>-0.974238</td>
      <td>5.084106</td>
      <td>0.001966</td>
    </tr>
    <tr>
      <th>magerr</th>
      <td>0.014054</td>
      <td>0.014062</td>
      <td>0.000090</td>
      <td>0.013198</td>
      <td>0.014289</td>
      <td>-5.911293</td>
      <td>38.424977</td>
      <td>0.001091</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>stats_Z_i_er <span class="op">=</span> lc_descriptive_stats_table_ZTF(<span class="st">'magerr'</span>, ZTF_i)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>stats_Z_i_er.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="49">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>mean</th>
      <th>median</th>
      <th>std</th>
      <th>amin</th>
      <th>amax</th>
      <th>skew</th>
      <th>kurtosis</th>
      <th>Amplitude</th>
    </tr>
    <tr>
      <th>index</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>magerr</th>
      <td>0.013091</td>
      <td>0.013459</td>
      <td>0.000607</td>
      <td>0.011990</td>
      <td>0.013925</td>
      <td>-0.514070</td>
      <td>-1.374902</td>
      <td>0.001935</td>
    </tr>
    <tr>
      <th>magerr</th>
      <td>0.012506</td>
      <td>0.012472</td>
      <td>0.000093</td>
      <td>0.012461</td>
      <td>0.012987</td>
      <td>3.139535</td>
      <td>9.975130</td>
      <td>0.000526</td>
    </tr>
    <tr>
      <th>magerr</th>
      <td>0.014519</td>
      <td>0.014490</td>
      <td>0.000056</td>
      <td>0.014481</td>
      <td>0.014778</td>
      <td>1.662839</td>
      <td>2.298835</td>
      <td>0.000298</td>
    </tr>
    <tr>
      <th>magerr</th>
      <td>0.013121</td>
      <td>0.012924</td>
      <td>0.000448</td>
      <td>0.012756</td>
      <td>0.016380</td>
      <td>2.606883</td>
      <td>11.937356</td>
      <td>0.003624</td>
    </tr>
    <tr>
      <th>magerr</th>
      <td>0.015054</td>
      <td>0.015051</td>
      <td>0.000048</td>
      <td>0.014756</td>
      <td>0.015298</td>
      <td>-0.152441</td>
      <td>9.746567</td>
      <td>0.000542</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
<section id="plotting-the-results-1" class="level4">
<h4 class="anchored" data-anchor-id="plotting-the-results-1">Plotting the results</h4>
<div class="cell" data-execution_count="50">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>stats_Z_g_er <span class="op">=</span> stats_Z_g_er.reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>stats_Z_r_er <span class="op">=</span> stats_Z_r_er.reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>stats_Z_i_er <span class="op">=</span> stats_Z_i_er.reset_index(drop<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>True
False
False
False</code></pre>
</div>
</div>
<div class="cell" data-execution_count="51">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>columns <span class="op">=</span> [<span class="st">'mean'</span>, <span class="st">'median'</span>, <span class="st">'std'</span>, <span class="st">'amin'</span>, <span class="st">'amax'</span>, <span class="st">'skew'</span>,<span class="st">'kurtosis'</span>,<span class="st">'Amplitude'</span>]</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">4</span>,<span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">30</span>,<span class="dv">18</span>)) <span class="co"># creating subplots with 2 columms and 3 rows</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> ax.flatten() <span class="co"># flatten the axes</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> tqdm(<span class="bu">range</span>(<span class="bu">len</span>(columns))): <span class="co">#plot the same type of graph for every property</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    ax[i].set_title(columns[i].upper(), fontproperties<span class="op">=</span>font) <span class="co"># the title of the graph is the column name</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    sns.histplot(data<span class="op">=</span>stats_L_er,x<span class="op">=</span>columns[i],ax<span class="op">=</span>ax[i], color<span class="op">=</span><span class="st">'#273E47'</span>, alpha<span class="op">=</span><span class="fl">0.3</span>) <span class="co"># blue</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>    sns.histplot(data<span class="op">=</span>stats_Z_g_er, x<span class="op">=</span>columns[i], ax<span class="op">=</span>ax[i], color<span class="op">=</span><span class="st">'#D8C99B'</span>,alpha<span class="op">=</span><span class="fl">0.3</span>) <span class="co"># light color</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>    sns.histplot(data<span class="op">=</span>stats_Z_r_er, x<span class="op">=</span>columns[i], ax<span class="op">=</span>ax[i], color<span class="op">=</span><span class="st">'#D8973C'</span>,alpha<span class="op">=</span><span class="fl">0.3</span>) <span class="co"># orange color</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>    sns.histplot(data<span class="op">=</span>stats_Z_i_er, x<span class="op">=</span>columns[i], ax<span class="op">=</span>ax[i], color<span class="op">=</span><span class="st">'#BD632F'</span>,alpha<span class="op">=</span><span class="fl">0.3</span>) <span class="co"># dark orange color</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>100%|██████████| 8/8 [00:13&lt;00:00,  1.73s/it]</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/figure-html/cell-35-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>From the graphs above, we can clearly see that many attributes from <code>LINEAR</code> and <code>ZTF</code> data do not match. 1. <strong>The mean graph</strong>: The most common mean error for <code>ZTF</code> in all filters is around 0.015, while for <code>LINEAR</code> it is around 0.025 with many light curves with much higher values.</p>
<ol start="2" type="1">
<li><p><strong>The median graph</strong>: Again, a huge difference. The most common median error for <code>ZTF</code> in all filters is again around 0.015 while for <code>LINEAR</code> its again from 0.025 to higher values, all the way to 0.125.</p></li>
<li><p><strong>The standard deviation graph</strong>: Most values for standard deviation in all <code>ZTF</code> filters is around 0 (very concentrated around the mean), while for <code>LINEAR</code> the values are a bit more spead out, taking on values from around 0.02 to 0.04.</p></li>
<li><p><strong>The minimum graph</strong>: Most values for the minimum error range around 0.01 for all <code>ZTF</code> filters, but for <code>LINEAR</code> the distribution doesn’t have a clear peak, but the values range from 0.01 to 0.04.</p></li>
<li><p><strong>The maximum graph</strong>: most values for the max are close to 0 for all <code>ZTF</code> filters, but for <code>LINEAR</code> the range is very large, from around 0 all the way o 0.6.</p></li>
<li><p><strong>The skew graph</strong>: most values for the skewness for all <code>ZTF</code> filters is around 0, but still fairly spread out in both directions. The <code>LINEAR</code> values are slightly above 0 and a bit spread out but not as much.</p></li>
<li><p><strong>The kurtosis graph</strong>: the only graph where both distributions are almost identical and the value is almost 0.</p></li>
<li><p><strong>The amplitude graph</strong>: most amplitudes for all <code>ZTF</code> filters are from 9 to around 0.01, while for <code>LINEAR</code> they range from 0.01 all the way to 0.6.</p></li>
</ol>
<p>From all of this we can conclude that <code>LINEAR</code> has much larger observational errors proportional to the <code>ZTF</code> errors.</p>
</section>
</section>
</section>
<section id="plotting-light-curves" class="level1">
<h1>Plotting light curves</h1>
<div class="cell" data-execution_count="60">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># LINEAR DATA</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="co"># -------------</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>lc_LINEAR()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/figure-html/cell-36-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="18">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># GREEN FILTER</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>lc_ZTF(ZTF_g, <span class="st">'.g'</span>, <span class="st">'green'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/figure-html/cell-37-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="20">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># RED FILTER</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>lc_ZTF(ZTF_g, <span class="st">'.r'</span>, <span class="st">'red'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/figure-html/cell-38-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="22">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># INFRARED FILTER</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>lc_ZTF(ZTF_g, <span class="st">'.m'</span>, <span class="st">'magenta'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="02_Understanding_and_accessing_LINEAR_and_ZTF_data_files/figure-html/cell-39-output-1.png" class="img-fluid"></p>
</div>
</div>
<hr>
<p>Now that we have a basic understanding of both <code>LINEAR</code> and <code>ZTF</code> data, we can continue analyzing the light curves themselves. We will analyze light curves in the following notebook by calculating their periods, fits and analyzing their periodograms in search for the Blazhko effect.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>